BEGIN READ ONLY;
SET LOCAL statement_timeout = '45s';
SET LOCAL lock_timeout = '2s';
WITH links AS (
 SELECT c.conrelid::regclass::text AS child,c.conname AS link,c.confrelid::regclass::text AS parent,
 format('SELECT count(*) AS orphans FROM %s ch WHERE %s AND NOT EXISTS (SELECT 1 FROM %s pa WHERE %s)',c.conrelid::regclass,
 (SELECT string_agg(format('ch.%I IS NOT NULL',a.attname),' AND ') FROM unnest(c.conkey) k JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k),
 c.confrelid::regclass,(SELECT string_agg(format('pa.%I=ch.%I',b.attname,a.attname),' AND ')
 FROM unnest(c.conkey,c.confkey) k(ck,pk) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.ck JOIN pg_attribute b ON b.attrelid=c.confrelid AND b.attnum=k.pk)) AS sql
 FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname='public' AND c.contype='f'
)
SELECT 'fk_orphans' AS section,jsonb_build_object('table',child,'link',link,'parent',parent,
 'orphans',((xpath('/table/row/orphans/text()',query_to_xml(sql,false,true,'')))[1]::text)::bigint) AS finding FROM links
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','driver_documents','column','driver_id','parent','drivers','orphans',(SELECT count(*) FROM public.driver_documents ch WHERE ch.driver_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.drivers pa WHERE pa.id=ch.driver_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','maintenance_plans','column','mant_template_id','parent','mant_plan_templates','orphans',(SELECT count(*) FROM public.maintenance_plans ch WHERE ch.mant_template_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.mant_plan_templates pa WHERE pa.id=ch.mant_template_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','lease_usage_records','column','vehicle_id','parent','vehicles','orphans',(SELECT count(*) FROM public.lease_usage_records ch WHERE ch.vehicle_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.vehicles pa WHERE pa.id=ch.vehicle_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','lease_gps_days','column','vehicle_id','parent','vehicles','orphans',(SELECT count(*) FROM public.lease_gps_days ch WHERE ch.vehicle_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.vehicles pa WHERE pa.id=ch.vehicle_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','fe_assets','column','vehicle_id','parent','vehicles','orphans',(SELECT count(*) FROM public.fe_assets ch WHERE ch.vehicle_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.vehicles pa WHERE pa.id=ch.vehicle_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','trip_advances','column','maintenance_request_id','parent','maintenance_requests','orphans',(SELECT count(*) FROM public.trip_advances ch WHERE ch.maintenance_request_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.maintenance_requests pa WHERE pa.id=ch.maintenance_request_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','kpi_dispatch_log','column','dispatch_id','parent','dispatches','orphans',(SELECT count(*) FROM public.kpi_dispatch_log ch WHERE ch.dispatch_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.dispatches pa WHERE pa.id=ch.dispatch_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','kpi_reprogramaciones','column','request_id','parent','transport_requests','orphans',(SELECT count(*) FROM public.kpi_reprogramaciones ch WHERE ch.request_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.transport_requests pa WHERE pa.id=ch.request_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','maintenance_invoices','column','proveedor_id','parent','maintenance_providers','orphans',(SELECT count(*) FROM public.maintenance_invoices ch WHERE ch.proveedor_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.maintenance_providers pa WHERE pa.id=ch.proveedor_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','driver_preuse_inspections','column','site_id','parent','sites','orphans',(SELECT count(*) FROM public.driver_preuse_inspections ch WHERE ch.site_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.sites pa WHERE pa.id=ch.site_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','dispatch_cargos','column','dispatch_id','parent','dispatches','orphans',(SELECT count(*) FROM public.dispatch_cargos ch WHERE ch.dispatch_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.dispatches pa WHERE pa.id=ch.dispatch_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','contract_budget_adjustments','column','budget_id','parent','contract_budgets','orphans',(SELECT count(*) FROM public.contract_budget_adjustments ch WHERE ch.budget_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.contract_budgets pa WHERE pa.id=ch.budget_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','contract_budget_adjustments','column','contract_id','parent','contracts','orphans',(SELECT count(*) FROM public.contract_budget_adjustments ch WHERE ch.contract_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.contracts pa WHERE pa.id=ch.contract_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','mant_asset_familia','column','vehicle_id','parent','vehicles','orphans',(SELECT count(*) FROM public.mant_asset_familia ch WHERE ch.vehicle_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.vehicles pa WHERE pa.id=ch.vehicle_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','desempeno_informes','column','user_id','parent','profiles','orphans',(SELECT count(*) FROM public.desempeno_informes ch WHERE ch.user_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles pa WHERE pa.id=ch.user_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','freight_rates','column','client_id','parent','clients','orphans',(SELECT count(*) FROM public.freight_rates ch WHERE ch.client_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.clients pa WHERE pa.id=ch.client_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','freight_rates','column','contract_id','parent','contracts','orphans',(SELECT count(*) FROM public.freight_rates ch WHERE ch.contract_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.contracts pa WHERE pa.id=ch.contract_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','transport_unloading_costs','column','contract_id','parent','contracts','orphans',(SELECT count(*) FROM public.transport_unloading_costs ch WHERE ch.contract_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.contracts pa WHERE pa.id=ch.contract_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','transport_unloading_costs','column','contract_service_id','parent','contract_services','orphans',(SELECT count(*) FROM public.transport_unloading_costs ch WHERE ch.contract_service_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.contract_services pa WHERE pa.id=ch.contract_service_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','transport_unloading_costs','column','expense_id','parent','dispatch_expenses','orphans',(SELECT count(*) FROM public.transport_unloading_costs ch WHERE ch.expense_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.dispatch_expenses pa WHERE pa.id=ch.expense_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','mant_turnos','column','vehicle_id','parent','vehicles','orphans',(SELECT count(*) FROM public.mant_turnos ch WHERE ch.vehicle_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.vehicles pa WHERE pa.id=ch.vehicle_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','mant_turnos','column','profile_id','parent','profiles','orphans',(SELECT count(*) FROM public.mant_turnos ch WHERE ch.profile_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles pa WHERE pa.id=ch.profile_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','kpi_historial','column','user_id','parent','profiles','orphans',(SELECT count(*) FROM public.kpi_historial ch WHERE ch.user_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles pa WHERE pa.id=ch.user_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','maintenance_request_events','column','request_id','parent','maintenance_requests','orphans',(SELECT count(*) FROM public.maintenance_request_events ch WHERE ch.request_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.maintenance_requests pa WHERE pa.id=ch.request_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','soporte_informes','column','user_id','parent','profiles','orphans',(SELECT count(*) FROM public.soporte_informes ch WHERE ch.user_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles pa WHERE pa.id=ch.user_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','notification_reads','column','user_id','parent','profiles','orphans',(SELECT count(*) FROM public.notification_reads ch WHERE ch.user_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles pa WHERE pa.id=ch.user_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','notif_prefs','column','user_id','parent','profiles','orphans',(SELECT count(*) FROM public.notif_prefs ch WHERE ch.user_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles pa WHERE pa.id=ch.user_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','dispatch_tercero_entregas','column','transport_request_id','parent','transport_requests','orphans',(SELECT count(*) FROM public.dispatch_tercero_entregas ch WHERE ch.transport_request_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.transport_requests pa WHERE pa.id=ch.transport_request_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','profiles','column','id','parent','auth.users','orphans',(SELECT count(*) FROM public.profiles ch WHERE ch.id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM auth.users pa WHERE pa.id=ch.id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_allocations','column','layer_id','parent','apt_layers','orphans',(SELECT count(*) FROM public.apt_allocations ch WHERE ch.layer_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_layers pa WHERE pa.id=ch.layer_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_allocations','column','exit_id','parent','apt_movements','orphans',(SELECT count(*) FROM public.apt_allocations ch WHERE ch.exit_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_movements pa WHERE pa.id=ch.exit_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_exit_class','column','exit_id','parent','apt_movements','orphans',(SELECT count(*) FROM public.apt_exit_class ch WHERE ch.exit_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_movements pa WHERE pa.id=ch.exit_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_layers','column','movement_id','parent','apt_movements','orphans',(SELECT count(*) FROM public.apt_layers ch WHERE ch.movement_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_movements pa WHERE pa.id=ch.movement_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_flow_layers','column','exit_id','parent','apt_flow_exits','orphans',(SELECT count(*) FROM public.apt_flow_layers ch WHERE ch.exit_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_flow_exits pa WHERE pa.id=ch.exit_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_flow_alloc','column','layer_id','parent','apt_flow_layers','orphans',(SELECT count(*) FROM public.apt_flow_alloc ch WHERE ch.layer_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_flow_layers pa WHERE pa.id=ch.layer_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_flow_alloc','column','exit_id','parent','apt_flow_exits','orphans',(SELECT count(*) FROM public.apt_flow_alloc ch WHERE ch.exit_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_flow_exits pa WHERE pa.id=ch.exit_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_flow_pieces','column','exit_id','parent','apt_flow_exits','orphans',(SELECT count(*) FROM public.apt_flow_pieces ch WHERE ch.exit_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_flow_exits pa WHERE pa.id=ch.exit_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_flow_pieces','column','layer_id','parent','apt_flow_layers','orphans',(SELECT count(*) FROM public.apt_flow_pieces ch WHERE ch.layer_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_flow_layers pa WHERE pa.id=ch.layer_id)))
UNION ALL SELECT 'soft_orphans',jsonb_build_object('table','apt_flow_pieces','column','root_id','parent','apt_flow_layers','orphans',(SELECT count(*) FROM public.apt_flow_pieces ch WHERE ch.root_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.apt_flow_layers pa WHERE pa.id=ch.root_id)));
ROLLBACK;
