-- Live catalog column shapes without data; tests install policies and constraints explicitly.
CREATE TABLE public."advance_reasons" ("requires_trip" boolean DEFAULT false,
"evidence_required" boolean DEFAULT false,
"max_amount" numeric,
"settlement_due_hours" integer,
"is_emergency" boolean DEFAULT false,
"creates_failure" boolean DEFAULT false,
"sort_order" integer DEFAULT 100,
"is_active" boolean DEFAULT true,
"code" text,
"label" text,
"description" text,
"charge_to" text,
"approval_by" text,
"default_expense_type" text);
CREATE TABLE public."ai_action_proposals" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"user_id" uuid,
"payload" jsonb,
"idempotency_key" uuid DEFAULT gen_random_uuid(),
"confirmed_by" uuid,
"confirmed_at" timestamp with time zone,
"result_ref" jsonb,
"created_at" timestamp with time zone DEFAULT now(),
"expires_at" timestamp with time zone,
"confirmed_payload" jsonb,
"latitude" numeric,
"longitude" numeric,
"device" jsonb,
"action_type" text,
"status" text,
"original_input" text,
"origin" text);
CREATE TABLE public."ai_query_audit" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"user_id" uuid,
"context_refs" jsonb,
"input_tokens" integer DEFAULT 0,
"output_tokens" integer DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"scope" text,
"model" text,
"tool_names" text[],
"status" text);
CREATE TABLE public."ai_request_log" ("id" bigint PRIMARY KEY,
"user_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"scope" text);
CREATE TABLE public."app_installations" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"user_id" uuid,
"device_id" uuid,
"build_number" integer,
"device" jsonb,
"last_seen_at" timestamp with time zone DEFAULT now(),
"created_at" timestamp with time zone DEFAULT now(),
"platform" text,
"installed_version" text);
CREATE TABLE public."app_update_events" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"user_id" uuid,
"release_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"device_id" uuid,
"build_number" integer,
"device" jsonb,
"installed_version" text,
"event" text,
"platform" text);
CREATE TABLE public."app_versions" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"build_number" integer,
"release_date" timestamp with time zone DEFAULT now(),
"mandatory" boolean DEFAULT false,
"mandatory_after" timestamp with time zone,
"minimum_supported_build" integer,
"created_at" timestamp with time zone DEFAULT now(),
"platform" text,
"channel" text,
"version" text,
"web_build_id" text,
"release_notes" text,
"minimum_supported_version" text,
"installer_url" text,
"artifact_sha256" text,
"status" text);
CREATE TABLE public."apt_aging_ranges" ("desde" integer,
"label" text);
CREATE TABLE public."apt_allocations" ("layer_id" bigint,
"exit_id" bigint,
"kg" numeric,
"fecha_ingreso" date,
"fecha_salida" date,
"dias" integer);
CREATE TABLE public."apt_exit_class" ("exit_id" bigint,
"fecha" date,
"kg" numeric,
"kg_asignado" numeric DEFAULT 0,
"kg_sin_entrada" numeric DEFAULT 0,
"lote" text,
"producto" text,
"clase" text);
CREATE TABLE public."apt_flow_alloc" ("layer_id" bigint,
"exit_id" bigint,
"kg" numeric);
CREATE TABLE public."apt_flow_exits" ("id" bigint PRIMARY KEY,
"fecha" date,
"kg" numeric,
"almacen" text,
"lote" text,
"producto" text,
"tipo" text,
"almacen_destino" text,
"lote_destino" text,
"documento" text,
"cliente" text,
"numrel" text,
"docrel" text,
"glosa" text);
CREATE TABLE public."apt_flow_layers" ("id" bigint PRIMARY KEY,
"exit_id" bigint,
"fecha" date,
"kg_in" numeric,
"kg_out" numeric DEFAULT 0,
"kg_saldo" numeric DEFAULT 0,
"almacen" text,
"lote" text,
"producto" text,
"tipo" text,
"almacen_origen" text,
"lote_origen" text,
"documento" text,
"glosa" text,
"cliente" text);
CREATE TABLE public."apt_flow_pieces" ("id" bigint PRIMARY KEY,
"es_saldo" boolean,
"exit_id" bigint,
"fecha_salida" date,
"layer_id" bigint,
"fecha_llegada" date,
"root_id" bigint,
"fecha_origen" date,
"kg" numeric,
"salida_tipo" text,
"documento" text,
"cliente" text,
"almacen" text,
"layer_tipo" text,
"almacen_previo" text,
"lote" text,
"producto" text,
"glosa" text,
"origen" text,
"root_almacen" text,
"root_lote" text);
CREATE TABLE public."apt_flow_state" ("id" integer DEFAULT 1 PRIMARY KEY,
"cutoff" date,
"data_min" date,
"rebuilt_at" timestamp with time zone,
"stats" jsonb);
CREATE TABLE public."apt_layers" ("movement_id" bigint,
"fecha_ingreso" date,
"fecha_entrega" date,
"cantidad" numeric,
"kg_in" numeric,
"kg_out" numeric DEFAULT 0,
"kg_saldo" numeric DEFAULT 0,
"kg_out_before_in" numeric DEFAULT 0,
"kg_out_fechado" numeric DEFAULT 0,
"out_kg_days" numeric DEFAULT 0,
"problema_info" boolean DEFAULT false,
"posible_cruce" boolean DEFAULT false,
"first_out" date,
"last_out" date,
"dias" integer,
"dias_saldo" integer,
"rango_orden" integer,
"tn_dias" numeric DEFAULT 0,
"estado" text,
"rango" text,
"cliente" text,
"cliente_fuente" text,
"lote" text,
"producto" text,
"numrel_op" text,
"glosa" text,
"familia" text,
"ipt" text,
"documento" text,
"docrel" text,
"unidad" text);
CREATE TABLE public."apt_movements" ("id" bigint PRIMARY KEY,
"upload_id" uuid,
"row_no" integer,
"raw" jsonb,
"active" boolean DEFAULT false,
"valid" boolean,
"fecha" date,
"lote_derivado" boolean DEFAULT false,
"cantidad" numeric,
"peso_unitario" numeric,
"peso_kg" numeric DEFAULT 0,
"fecha_entrega" date,
"almacen" text,
"contrato" text,
"kind" text,
"invalid_reason" text,
"documento" text,
"tipodocto" text,
"bodega" text,
"numrel" text,
"lote_origen" text,
"lote" text,
"docrel" text,
"cliente" text,
"ruc" text,
"producto" text,
"glosa" text,
"familia" text,
"ipt" text,
"unidad" text);
CREATE TABLE public."apt_settings" ("id" integer DEFAULT 1 PRIMARY KEY,
"cutoff_date" date,
"tolerance" numeric DEFAULT 0.02,
"alert_days" integer DEFAULT 60,
"updated_by" uuid,
"updated_at" timestamp with time zone DEFAULT now());
CREATE TABLE public."apt_state" ("id" integer DEFAULT 1 PRIMARY KEY,
"cutoff" date,
"data_min" date,
"data_max" date,
"rebuilt_at" timestamp with time zone);
CREATE TABLE public."apt_uploads" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"applied_at" timestamp with time zone,
"summary" jsonb,
"file_name" text,
"status" text);
CREATE TABLE public."authorized_locations" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"latitude" double precision,
"longitude" double precision,
"radius_km" double precision DEFAULT 0.5,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone,
"updated_at" timestamp with time zone,
"name" text,
"address" text);
CREATE TABLE public."budget_extensions" ("id" uuid PRIMARY KEY,
"work_order_id" uuid,
"requested_amount" numeric,
"requested_by" uuid,
"approved_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"reason" text,
"status" character varying);
CREATE TABLE public."caja_settings" ("id" boolean DEFAULT true PRIMARY KEY,
"double_approval_threshold" numeric,
"settlement_due_hours" integer DEFAULT 48,
"default_km_per_gallon" numeric DEFAULT 10,
"fuel_efficiency_tolerance_pct" numeric DEFAULT 25,
"updated_at" timestamp with time zone DEFAULT now(),
"updated_by" uuid,
"fuel_price_per_gallon" numeric DEFAULT 16,
"budget_tolerance_pct" numeric DEFAULT 10);
CREATE TABLE public."carriers" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"business_name" character varying,
"tax_id" character varying,
"type" character varying,
"contact_phone" character varying);
CREATE TABLE public."cash_box_closures" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"box_id" uuid,
"closure_date" date,
"system_balance" numeric,
"counted_balance" numeric,
"difference" numeric,
"movement_id" uuid,
"closed_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"notes" text);
CREATE TABLE public."cash_boxes" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"site_id" uuid,
"responsible_id" uuid,
"min_balance" numeric DEFAULT 0,
"max_balance" numeric,
"allow_negative" boolean DEFAULT false,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"created_by" uuid,
"code" text,
"name" text,
"box_type" text,
"currency" text);
CREATE TABLE public."cash_funds" ("date" timestamp with time zone DEFAULT now(),
"given_by" uuid,
"received_by" uuid,
"amount" numeric,
"trip_id" uuid,
"work_order_id" uuid,
"contract_id" uuid,
"cost_center_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"code" character varying,
"currency" character varying,
"reason" text,
"vehicle_plate" character varying,
"status" character varying);
CREATE TABLE public."cash_movements" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"box_id" uuid,
"direction" smallint,
"amount" numeric,
"driver_id" uuid,
"dispatch_id" uuid,
"advance_id" uuid,
"expense_id" uuid,
"settlement_id" uuid,
"reverses_id" uuid,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"movement_type" text,
"payment_method" text,
"reference" text,
"description" text);
CREATE TABLE public."cash_settlements" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"cash_fund_id" uuid,
"total_fund" numeric DEFAULT 0,
"total_expenses" numeric DEFAULT 0,
"balance" numeric DEFAULT 0,
"submitted_at" timestamp with time zone DEFAULT now(),
"approved_at" timestamp with time zone,
"approved_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"status" character varying);
CREATE TABLE public."checklist_items" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"template_id" uuid,
"is_critical" boolean DEFAULT false,
"position" integer DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"requires_photo" boolean DEFAULT false,
"text" text,
"response_type" text,
"code" text,
"help_text" text);
CREATE TABLE public."checklist_templates" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"requires_signature" boolean DEFAULT false,
"requires_odometer" boolean DEFAULT true,
"name" text,
"type" text,
"code" text,
"asset_types" text[],
"description" text);
CREATE TABLE public."clients" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"sunat_verified_at" timestamp with time zone,
"business_name" character varying,
"tax_id" character varying,
"contact_name" character varying,
"contact_email" character varying,
"contact_phone" character varying,
"address" text,
"email" character varying,
"phone" character varying,
"sunat_status" text);
CREATE TABLE public."contract_budget_adjustments" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"budget_id" uuid,
"contract_id" uuid,
"old_value" numeric,
"new_value" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"field" text,
"reason" text);
CREATE TABLE public."contract_budgets" ("balance_pen" numeric,
"id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"contract_id" uuid,
"allocated_usd" numeric DEFAULT 0,
"exchange_rate" numeric DEFAULT 3.75,
"allocated_pen" numeric DEFAULT 0,
"reserved_pen" numeric DEFAULT 0,
"consumed_pen" numeric DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"concept" character varying);
CREATE TABLE public."contract_service_peso_apt" ("service_id" uuid,
"kg" numeric,
"encontradas" integer DEFAULT 0,
"calculado_at" timestamp with time zone DEFAULT now(),
"guias" text,
"faltan" text);
CREATE TABLE public."contract_services" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"contract_id" uuid,
"amount_pen" numeric,
"service_date" date DEFAULT CURRENT_DATE,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"hours" numeric,
"dispatch_id" uuid,
"budget_contract_id" uuid,
"voided_by" uuid,
"voided_at" timestamp with time zone,
"void_requested_by" uuid,
"service_type" character varying,
"description" text,
"status" character varying,
"plate" character varying,
"driver_name" character varying,
"provider_ruc" character varying,
"provider_name" character varying,
"category" character varying,
"referral_guide" text,
"void_reason" text);
CREATE TABLE public."contract_user_assignments" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"contract_id" uuid,
"user_id" uuid,
"active" boolean DEFAULT true,
"assigned_at" timestamp with time zone DEFAULT now(),
"ended_at" timestamp with time zone,
"assigned_by" uuid,
"ended_by" uuid,
"role" text,
"reason" text);
CREATE TABLE public."contracts" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"type" text,
"client_id" uuid,
"is_new" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"total_weight_kg" numeric DEFAULT 0,
"total_volume_m3" numeric DEFAULT 0,
"parent_contract_id" uuid,
"site_id" uuid,
"subcontract_id" uuid,
"created_by" uuid,
"code" character varying,
"status" character varying,
"destination_department" character varying,
"destination_province" character varying,
"destination_district" character varying,
"destination_address" character varying);
CREATE TABLE public."cost_centers" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"code" character varying,
"name" character varying,
"type" character varying,
"description" text);
CREATE TABLE public."daily_tracking_links" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"planning_date" date,
"tracking_token" uuid,
"expires_at" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"tracking_pin" text);
CREATE TABLE public."delivery_conformities" ("dispatch_id" uuid,
"request_id" uuid,
"arrived_at" timestamp with time zone,
"current_submission_id" uuid,
"updated_at" timestamp with time zone DEFAULT now(),
"state" text);
CREATE TABLE public."delivery_portal_attempts" ("window_at" timestamp with time zone DEFAULT now(),
"attempts" integer DEFAULT 0,
"fingerprint" text);
CREATE TABLE public."delivery_reviews" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"submission_id" uuid,
"reviewed_by" uuid,
"reviewed_at" timestamp with time zone DEFAULT now(),
"decision" text,
"reason" text);
CREATE TABLE public."delivery_submissions" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"operation_id" uuid,
"dispatch_id" uuid,
"request_id" uuid,
"submitted_by" uuid,
"captured_at" timestamp with time zone,
"submitted_at" timestamp with time zone DEFAULT now(),
"photos" text[],
"guide_number" text,
"received_by" text,
"note" text,
"source" text);
CREATE TABLE public."deprecated_expense_liquidations" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"driver_id" uuid,
"amount" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"expense_type" character varying,
"currency" character varying,
"receipt_number" character varying,
"photo_url" text,
"status" character varying);
CREATE TABLE public."deprecated_expense_records" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"cash_fund_id" uuid,
"issue_date" date,
"issue_time" time without time zone,
"subtotal" numeric DEFAULT 0,
"igv" numeric DEFAULT 0,
"total_amount" numeric,
"ocr_confidence_score" numeric,
"ocr_raw_data" jsonb,
"anomalies" jsonb,
"trip_id" uuid,
"work_order_id" uuid,
"contract_id" uuid,
"cost_center_id" uuid,
"reported_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"transport_request_id" uuid,
"is_billable" boolean DEFAULT false,
"category" character varying,
"provider_ruc" character varying,
"provider_name" character varying,
"document_type" character varying,
"document_serial" character varying,
"document_number" character varying,
"currency" character varying,
"description" text,
"evidence_original_url" text,
"evidence_processed_url" text,
"status" character varying,
"vehicle_plate" character varying);
CREATE TABLE public."deprecated_expenses" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"amount" numeric,
"reported_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"cost_center_id" uuid,
"maintenance_record_id" uuid,
"expense_type" character varying,
"currency" character varying,
"receipt_number" character varying,
"description" text,
"status" character varying);
CREATE TABLE public."desempeno_informes" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"user_id" uuid,
"periodo" date,
"kpis" jsonb,
"enviado_at" timestamp with time zone DEFAULT now(),
"actualizado_at" timestamp with time zone DEFAULT now(),
"dias_desde_cierre" integer DEFAULT 0,
"dias_atraso" integer DEFAULT 0,
"revisado_por" uuid,
"revisado_at" timestamp with time zone,
"rol" text,
"logros" text,
"problemas" text,
"acciones" text,
"estado" text,
"comentario" text);
CREATE TABLE public."dispatch_cargos" ("dispatch_id" uuid,
"recibido_at" timestamp with time zone DEFAULT now(),
"recibido_by" uuid,
"file_path" text,
"notas" text);
CREATE TABLE public."dispatch_crew" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"profile_id" uuid,
"assigned_by" uuid,
"assigned_at" timestamp with time zone DEFAULT now(),
"removed_by" uuid,
"removed_at" timestamp with time zone,
"crew_role" text);
CREATE TABLE public."dispatch_documents" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"transport_request_id" uuid,
"size_bytes" bigint,
"uploaded_by" uuid,
"uploaded_at" timestamp with time zone DEFAULT now(),
"voided_at" timestamp with time zone,
"voided_by" uuid,
"auditor_signed_date" date,
"auditor_signature_confirmed" boolean DEFAULT false,
"doc_type" text,
"cargo_type" text,
"document_number" text,
"file_path" text,
"file_name" text,
"mime_type" text,
"notes" text,
"void_reason" text,
"auditor_name" text);
CREATE TABLE public."dispatch_events" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"latitude" numeric,
"longitude" numeric,
"created_at" timestamp with time zone,
"user_id" uuid,
"payload" jsonb,
"device" jsonb,
"idempotency_key" uuid,
"created_by_user" uuid,
"event_type" character varying,
"description" text,
"created_by" character varying,
"origin" text);
CREATE TABLE public."dispatch_expense_events" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"expense_id" uuid,
"amount" numeric,
"actor_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"action" text,
"from_status" text,
"to_status" text,
"comment" text);
CREATE TABLE public."dispatch_expenses" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"amount" numeric DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"driver_id" uuid,
"created_by" uuid,
"latitude" numeric,
"longitude" numeric,
"client_operation_id" uuid,
"fuel_gallons" numeric,
"fuel_odometer" numeric,
"updated_at" timestamp with time zone DEFAULT now(),
"site_id" uuid,
"expense_date" date,
"is_billable" boolean DEFAULT false,
"transport_request_id" uuid,
"original_amount" numeric,
"approved_amount" numeric,
"reviewed_by" uuid,
"reviewed_at" timestamp with time zone,
"first_approved_by" uuid,
"first_approved_at" timestamp with time zone,
"alerts" jsonb,
"fuel_station_id" uuid,
"cash_box_id" uuid,
"fuel_invoice_id" uuid,
"advance_id" uuid,
"expense_type" character varying,
"description" text,
"receipt_url" text,
"status" text,
"source" text,
"vehicle_plate" text,
"currency" text,
"document_type" text,
"document_series" text,
"document_number" text,
"provider_ruc" text,
"provider_name" text,
"review_comment" text,
"paid_by" text);
CREATE TABLE public."dispatch_request_freight" ("dispatch_id" uuid,
"request_id" uuid,
"contract_id" uuid,
"amount_pen" numeric,
"service_id" uuid,
"status" text);
CREATE TABLE public."dispatch_requests" ("dispatch_id" uuid,
"transport_request_id" uuid,
"sequence_order" integer,
"created_at" timestamp with time zone DEFAULT now(),
"leg_planned_km" numeric DEFAULT 0,
"leg_actual_km" numeric DEFAULT 0,
"arrival_odometer" numeric DEFAULT 0,
"leg_gps_complete" boolean,
"arrival_lat" numeric,
"arrival_lon" numeric,
"status" character varying,
"document_type" character varying,
"document_number" character varying);
CREATE TABLE public."dispatch_tercero_enlaces" ("dispatch_id" uuid,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"expires_at" timestamp with time zone,
"revoked_at" timestamp with time zone,
"last_used_at" timestamp with time zone,
"token" text,
"access_code" text);
CREATE TABLE public."dispatch_tercero_entregas" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"transport_request_id" uuid,
"entregado_at" timestamp with time zone,
"registrado_por" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"fuente" text,
"recibido_por" text,
"foto_path" text,
"nota" text);
CREATE TABLE public."dispatch_work_orders" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"work_order_id" uuid,
"sequence_order" integer,
"delivery_time" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"delivery_status" character varying);
CREATE TABLE public."dispatches" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"carrier_id" uuid,
"vehicle_id" uuid,
"driver_id" uuid,
"departure_time" timestamp with time zone,
"estimated_arrival" timestamp with time zone,
"total_weight" numeric DEFAULT 0,
"total_volume" numeric DEFAULT 0,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"scheduled_departure" timestamp with time zone,
"estimated_distance_km" numeric DEFAULT 0,
"estimated_km" numeric,
"estimated_cost" numeric,
"auxiliary_id" uuid,
"freight_cost" numeric DEFAULT 0.00,
"contract_id" uuid,
"tracking_token" uuid,
"tracking_expires_at" timestamp with time zone,
"start_lat" numeric,
"start_lon" numeric,
"actual_distance_km" numeric DEFAULT 0,
"last_lat" numeric,
"last_lon" numeric,
"last_gps_at" timestamp with time zone,
"gps_coverage_complete" boolean,
"return_actual_km" numeric,
"return_gps_complete" boolean,
"returned_at" timestamp with time zone,
"site_id" uuid,
"end_odometer" numeric,
"arrival_time" timestamp with time zone,
"liquidation_data" jsonb,
"start_odometer" numeric,
"docs_required" boolean DEFAULT false,
"docs_ready_at" timestamp with time zone,
"docs_ready_by" uuid,
"docs_reissue" boolean DEFAULT false,
"docs_reissue_at" timestamp with time zone,
"freight_breakdown" jsonb,
"tercero_salida_at" timestamp with time zone,
"tercero_entrega_at" timestamp with time zone,
"cost_center_id" uuid,
"dispatch_number" character varying,
"status" character varying,
"driver_name" character varying,
"vehicle_plate" character varying,
"auxiliary_name" text,
"tracking_pin" text,
"docs_reissue_reason" text,
"modalidad" text,
"tercero_conductor" text,
"tercero_telefono" text,
"tercero_doc" text);
CREATE TABLE public."document_liquidations" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"transport_request_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"document_type" character varying,
"document_number" character varying,
"photo_url" text,
"status" character varying);
CREATE TABLE public."driver_app_presence" ("driver_id" uuid,
"profile_id" uuid,
"last_seen_at" timestamp with time zone DEFAULT now(),
"disconnected_at" timestamp with time zone,
"latitude" numeric,
"longitude" numeric,
"accuracy_m" numeric,
"speed_mps" numeric,
"recorded_at" timestamp with time zone,
"gps_state" text);
CREATE TABLE public."driver_checklists" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"driver_id" uuid,
"checklist_data" jsonb,
"location_lat" numeric,
"location_lon" numeric,
"is_approved" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"inspection_id" uuid,
"vehicle_plate" character varying,
"photo_url" text);
CREATE TABLE public."driver_documents" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"driver_id" uuid,
"issue_date" date,
"expiry_date" date,
"created_at" timestamp with time zone DEFAULT now(),
"is_active" boolean DEFAULT true,
"updated_at" timestamp with time zone DEFAULT now(),
"doc_type" text,
"doc_number" text,
"category" text,
"file_url" text,
"issuer" text,
"notes" text);
CREATE TABLE public."driver_operation_receipts" ("operation_id" uuid,
"user_id" uuid,
"result" jsonb,
"created_at" timestamp with time zone DEFAULT now(),
"action_type" text);
CREATE TABLE public."driver_preuse_inspections" ("operation_id" uuid,
"record_sequence" bigint,
"inspection_id" uuid,
"driver_id" uuid,
"submitted_by" uuid,
"site_id" uuid,
"unit_revision" uuid,
"operation_date" date,
"captured_at" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"soat_expiration" date,
"technical_review_expiration" date,
"answers" jsonb,
"vehicle_operational" boolean,
"can_operate" boolean,
"signature" jsonb,
"vehicle_plate" text,
"driver_name" text,
"license" text,
"observation" text,
"inspector_name" text);
CREATE TABLE public."driver_preuse_unit_events" ("revision" uuid,
"event_sequence" bigint,
"driver_id" uuid,
"operation_date" date,
"selected_at" timestamp with time zone DEFAULT now(),
"vehicle_plate" text);
CREATE TABLE public."driver_preuse_units" ("driver_id" uuid,
"revision" uuid,
"operation_date" date,
"selected_at" timestamp with time zone DEFAULT now(),
"vehicle_plate" text);
CREATE TABLE public."drivers" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"carrier_id" uuid,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"profile_id" uuid,
"license_expiration" date,
"updated_at" timestamp with time zone DEFAULT now(),
"first_name" character varying,
"last_name" character varying,
"document_number" character varying,
"license_number" character varying,
"phone" character varying,
"license_category" character varying,
"pin" character varying);
CREATE TABLE public."evidences" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_work_order_id" uuid,
"uploaded_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"file_url" text,
"file_type" character varying);
CREATE TABLE public."expense_audit_logs" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"record_id" uuid,
"user_id" uuid,
"old_value" jsonb,
"new_value" jsonb,
"created_at" timestamp with time zone DEFAULT now(),
"record_type" character varying,
"action" character varying);
CREATE TABLE public."expense_categories" ("requires_receipt" boolean DEFAULT true,
"max_amount" numeric,
"is_active" boolean DEFAULT true,
"sort_order" integer DEFAULT 100,
"code" text,
"label" text,
"group_label" text,
"ledger_category" text,
"account_code" text,
"budget_key" text);
CREATE TABLE public."fe_assets" ("anio_fab" integer,
"capacidad_kg" numeric,
"valor_reposicion" numeric,
"vida_util" integer,
"activo" boolean DEFAULT true,
"editado" boolean DEFAULT false,
"updated_at" timestamp with time zone DEFAULT now(),
"vehicle_id" uuid,
"code" text,
"nombre" text,
"clase" text,
"tipo" text,
"marca" text,
"vehicle_plate" text,
"alias" text[]);
CREATE TABLE public."fe_fuel_month" ("mes" date,
"upload_id" uuid,
"galones" numeric,
"soles" numeric,
"km" numeric,
"precio" numeric,
"glp" boolean DEFAULT false,
"asset_code" text);
CREATE TABLE public."fe_hour_readings" ("id" bigint PRIMARY KEY,
"fecha" date,
"horas" numeric,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"asset_code" text,
"nota" text);
CREATE TABLE public."fe_ipr_eval" ("obsolescencia" integer,
"adecuacion" integer,
"updated_by" uuid,
"updated_at" timestamp with time zone DEFAULT now(),
"code" text,
"nota" text);
CREATE TABLE public."fe_maint" ("id" bigint PRIMARY KEY,
"upload_id" uuid,
"fecha" date,
"monto" numeric DEFAULT 0,
"km_hrs" numeric,
"mayor" boolean DEFAULT false,
"dias_fuera" numeric,
"prox_mantto" numeric,
"fecha_ingreso" date,
"fecha_salida" date,
"amortizable" boolean DEFAULT false,
"asset_code" text,
"proveedor" text,
"factura" text,
"tipo" text,
"categoria" text,
"area" text,
"detalle" text,
"tipo_real" text,
"sistema" text);
CREATE TABLE public."fe_raw" ("id" bigint PRIMARY KEY,
"upload_id" uuid,
"row_no" integer,
"data" jsonb,
"kind" text);
CREATE TABLE public."fe_settings" ("id" integer DEFAULT 1 PRIMARY KEY,
"desde" date,
"corte" date,
"params" jsonb,
"updated_at" timestamp with time zone DEFAULT now(),
"updated_by" uuid);
CREATE TABLE public."fe_trips" ("id" bigint PRIMARY KEY,
"upload_id" uuid,
"fecha" date,
"km" numeric,
"kg" numeric,
"m3" numeric,
"espera_h" numeric,
"programado" boolean,
"horas" numeric,
"ayudantes" numeric,
"distrito" text,
"conductor" text,
"asset_code" text,
"actividad" text,
"area" text,
"cliente" text,
"provincia" text,
"guia" text,
"descarga" text);
CREATE TABLE public."fe_uploads" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"summary" jsonb,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"applied_at" timestamp with time zone,
"file_name" text,
"status" text);
CREATE TABLE public."freight_rates" ("id" uuid PRIMARY KEY,
"capacity_ton" numeric,
"rate" numeric,
"created_at" timestamp with time zone,
"updated_at" timestamp with time zone,
"client_id" uuid,
"contract_id" uuid,
"client_price" numeric,
"valid_from" date DEFAULT CURRENT_DATE,
"valid_to" date,
"is_active" boolean DEFAULT true,
"updated_by" uuid,
"origin" character varying,
"district" character varying,
"zone" character varying,
"vehicle_type" character varying,
"plate_number" character varying,
"concept" text,
"vehicle_class" text,
"department" text,
"province" text,
"scope" text,
"rate_basis" text,
"notes" text);
CREATE TABLE public."fuel_station_invoices" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"station_id" uuid,
"issue_date" date,
"period_start" date,
"period_end" date,
"amount" numeric,
"gallons" numeric,
"loads_amount" numeric,
"loads_gallons" numeric,
"loads_count" integer,
"difference_amount" numeric,
"reconciled_by" uuid,
"reconciled_at" timestamp with time zone,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"document_series" text,
"document_number" text,
"status" text,
"notes" text);
CREATE TABLE public."fuel_stations" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"has_credit" boolean DEFAULT false,
"credit_limit" numeric,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"ruc" text,
"name" text,
"address" text,
"billing_cycle" text);
CREATE TABLE public."geofences" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"coordinates" jsonb,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"name" text,
"color" text,
"type" text,
"description" text);
CREATE TABLE public."inspection_results" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"inspection_id" uuid,
"item_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"response" text,
"observation" text,
"photo_url" text);
CREATE TABLE public."inspections" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"driver_id" uuid,
"template_id" uuid,
"date" timestamp with time zone DEFAULT now(),
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"dispatch_id" uuid,
"odometer" numeric,
"hours" numeric,
"location_lat" numeric,
"location_lon" numeric,
"site_id" uuid,
"failed_items" integer DEFAULT 0,
"critical_failures" integer DEFAULT 0,
"vehicle_plate" text,
"global_result" text,
"inspection_type" text,
"signature_url" text,
"notes" text,
"source" text);
CREATE TABLE public."inventory_transactions" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"part_id" uuid,
"quantity" numeric,
"reference_id" uuid,
"date" timestamp with time zone DEFAULT now(),
"created_at" timestamp with time zone DEFAULT now(),
"spare_part_id" uuid,
"total_cost" numeric,
"work_order_reference" uuid,
"created_by" uuid,
"unit_cost" numeric,
"balance_after" numeric,
"average_cost_after" numeric,
"provider_id" uuid,
"transaction_type" character varying,
"type" text,
"reference_document" text,
"reason" text);
CREATE TABLE public."kpi_dispatch_log" ("id" bigint PRIMARY KEY,
"dispatch_id" uuid,
"at" timestamp with time zone DEFAULT now(),
"by" uuid,
"estado_anterior" text,
"estado_nuevo" text,
"origen" text);
CREATE TABLE public."kpi_historial" ("sujeto" uuid,
"periodo" date,
"user_id" uuid,
"indice" numeric,
"cobertura" numeric,
"ficha" jsonb,
"calculado_at" timestamp with time zone DEFAULT now(),
"rol" text,
"nombre" text,
"calificacion" text);
CREATE TABLE public."kpi_parametros" ("meta" numeric,
"peso" numeric DEFAULT 0,
"orden" integer DEFAULT 0,
"rol" text,
"codigo" text,
"nombre" text,
"grupo" text,
"unidad" text,
"sentido" text,
"descripcion" text);
CREATE TABLE public."kpi_reprogramaciones" ("id" bigint PRIMARY KEY,
"request_id" uuid,
"fecha_anterior" date,
"fecha_nueva" date,
"at" timestamp with time zone DEFAULT now(),
"by" uuid,
"causa" text,
"detalle" text);
CREATE TABLE public."kpi_roles" ("informe" boolean DEFAULT true,
"orden" integer DEFAULT 0,
"rol" text,
"nombre" text,
"permisos" text[],
"nombres_rol" text[]);
CREATE TABLE public."lease_gps_days" ("vehicle_id" uuid,
"fecha" date,
"km" numeric DEFAULT 0,
"odometro" numeric,
"paradas" numeric,
"tiempo" text,
"nota" text);
CREATE TABLE public."lease_settlement_sends" ("id" bigint PRIMARY KEY,
"settlement_id" uuid,
"sent_at" timestamp with time zone DEFAULT now(),
"sent_by" uuid,
"sent_to" text,
"cc" text,
"channel" text,
"note" text);
CREATE TABLE public."lease_settlements" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"contract_id" uuid,
"vehicle_id" uuid,
"period_start" date,
"period_end" date,
"days" integer,
"hours_used" numeric DEFAULT 0,
"km_used" numeric DEFAULT 0,
"downtime_days" numeric DEFAULT 0,
"base_amount" numeric,
"excess_km" numeric DEFAULT 0,
"excess_km_amount" numeric DEFAULT 0,
"excess_hours" numeric DEFAULT 0,
"excess_hours_amount" numeric DEFAULT 0,
"downtime_discount" numeric DEFAULT 0,
"other_discounts" numeric DEFAULT 0,
"penalties" numeric DEFAULT 0,
"consumptions" numeric DEFAULT 0,
"additional_costs" numeric DEFAULT 0,
"subtotal" numeric,
"tax" numeric,
"total" numeric,
"detail" jsonb,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"approved_by" uuid,
"approved_at" timestamp with time zone,
"status" text,
"notes" text);
CREATE TABLE public."lease_usage_records" ("id" bigint PRIMARY KEY,
"vehicle_id" uuid,
"fecha" date,
"km" numeric DEFAULT 0,
"km_entrega" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"fuente" text,
"tipo_operacion" text,
"guia" text,
"ot_oc" text,
"area" text,
"conductor" text,
"licencia" text,
"cliente" text,
"zona" text,
"destino" text,
"propiedad" text,
"observaciones" text);
CREATE TABLE public."maintenance_invoices" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"fecha" date,
"monto" numeric DEFAULT 0,
"proveedor_id" uuid,
"orden_trabajo_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"numero" character varying);
CREATE TABLE public."maintenance_plans" ("id" uuid PRIMARY KEY,
"frequency_km" integer,
"frequency_days" integer,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone,
"updated_at" timestamp with time zone,
"site_id" uuid,
"next_due_km" numeric,
"next_due_odometer" numeric,
"next_due_date" date,
"frequency_hours" numeric,
"standard_tasks" jsonb,
"expected_parts" jsonb,
"last_performed_odometer" numeric,
"last_performed_hours" integer,
"last_performed_km" numeric,
"last_performed_date" date,
"next_due_hours" integer,
"mant_template_id" bigint,
"name" character varying,
"vehicle_type" character varying,
"activity_description" text,
"criticality" character varying,
"responsible_role" character varying,
"vehicle_plate" text,
"mant_base_origen" text);
CREATE TABLE public."maintenance_providers" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"sla_hours" numeric,
"default_warranty_days" integer,
"default_warranty_km" integer,
"ruc" character varying,
"business_name" character varying,
"address" text,
"contact_name" character varying,
"contact_phone" character varying,
"specialty" character varying,
"status" character varying,
"provider_type" text,
"email" text,
"payment_terms" text,
"notes" text);
CREATE TABLE public."maintenance_request_events" ("id" bigint PRIMARY KEY,
"request_id" uuid,
"at" timestamp with time zone DEFAULT now(),
"by" uuid,
"evento" text,
"estado_anterior" text,
"estado_nuevo" text,
"detalle" text);
CREATE TABLE public."maintenance_requests" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"driver_id" uuid,
"dispatch_id" uuid,
"reported_at" timestamp with time zone DEFAULT now(),
"location_lat" numeric,
"location_lon" numeric,
"odometer_at_report" numeric,
"work_order_id" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"can_continue" boolean DEFAULT true,
"reported_by" uuid,
"horometer" numeric,
"evidence" jsonb,
"assigned_to" uuid,
"source_ref_id" uuid,
"site_id" uuid,
"scheduled_for" date,
"validated_at" timestamp with time zone,
"validated_by" uuid,
"closed_at" timestamp with time zone,
"first_response_at" timestamp with time zone,
"first_response_by" uuid,
"vehicle_plate" text,
"description" text,
"severity" text,
"status" text,
"photo_url" text,
"audio_url" text,
"notes" text,
"failure_category" text,
"client_operation_id" text,
"source" text,
"diagnosis" text,
"discard_reason" text);
CREATE TABLE public."maintenance_work_orders" ("id" uuid PRIMARY KEY,
"vehicle_id" uuid,
"source_id" uuid,
"responsible_id" uuid,
"start_date" date,
"estimated_end_date" date,
"actual_end_date" date,
"downtime_hours" numeric DEFAULT 0,
"created_at" timestamp with time zone,
"updated_at" timestamp with time zone,
"provider_id" uuid,
"site_id" uuid,
"mechanic_id" uuid,
"tasks" jsonb,
"labor_cost" numeric DEFAULT 0,
"parts_cost" numeric DEFAULT 0,
"services_cost" numeric DEFAULT 0,
"total_cost" numeric DEFAULT 0,
"evidence_urls" jsonb,
"downtime_start" timestamp with time zone,
"downtime_end" timestamp with time zone,
"approved_by" uuid,
"provider_evaluation_score" integer,
"plan_id" uuid,
"approved_at" timestamp with time zone,
"validated_by" uuid,
"validated_at" timestamp with time zone,
"closed_by" uuid,
"closed_at" timestamp with time zone,
"release_result" jsonb,
"finished_at" timestamp with time zone,
"rework_count" integer DEFAULT 0,
"approved_quote_id" uuid,
"warranty_reviewed_at" timestamp with time zone,
"warranty_provider_id" uuid,
"evaluated_at" timestamp with time zone,
"ot_code" character varying,
"source_type" character varying,
"priority" character varying,
"description" text,
"workshop_name" character varying,
"status" character varying,
"diagnostic" text,
"activities_performed" text,
"notes" text,
"order_type" character varying,
"diagnosis" text,
"provider_evaluation_notes" text,
"ot_number" character varying,
"vehicle_plate" text,
"type" character varying,
"cancel_reason" text,
"warranty_decision" text,
"warranty_notes" text);
CREATE TABLE public."mant_asset_familia" ("vehicle_id" uuid,
"updated_at" timestamp with time zone DEFAULT now(),
"familia" text,
"nota" text);
CREATE TABLE public."mant_familias" ("checklist" jsonb,
"orden" integer DEFAULT 0,
"code" text,
"nombre" text,
"lectura" text,
"checklist_frecuencia" text);
CREATE TABLE public."mant_plan_templates" ("id" bigint PRIMARY KEY,
"frecuencia_km" integer,
"frecuencia_horas" integer,
"frecuencia_dias" integer,
"tareas" jsonb,
"activo" boolean DEFAULT true,
"costo_ref" numeric,
"familia" text,
"servicio" text,
"sistema" text,
"fuente" text,
"patron" text,
"incluye" text);
CREATE TABLE public."mant_settings" ("id" integer DEFAULT 1 PRIMARY KEY,
"umbral_cotizacion" numeric DEFAULT 5000,
"meta_correctivo" numeric DEFAULT 25,
"updated_at" timestamp with time zone DEFAULT now());
CREATE TABLE public."mant_setup_log" ("id" bigint PRIMARY KEY,
"created_at" timestamp with time zone DEFAULT now(),
"paso" text,
"detalle" text);
CREATE TABLE public."mant_sistemas" ("orden" integer,
"code" text,
"nombre" text);
CREATE TABLE public."mant_turnos" ("id" bigint PRIMARY KEY,
"created_at" timestamp with time zone DEFAULT now(),
"vehicle_id" uuid,
"profile_id" uuid,
"horas" numeric,
"checklist" jsonb,
"fallas" integer DEFAULT 0,
"vehicle_plate" text,
"tipo" text,
"estado_lectura" text,
"observaciones" text);
CREATE TABLE public."notif_prefs" ("user_id" uuid,
"silenciada" boolean DEFAULT true,
"categoria" text);
CREATE TABLE public."notif_reglas" ("al_solicitante" boolean DEFAULT false,
"activo" boolean DEFAULT true,
"updated_at" timestamp with time zone DEFAULT now(),
"permisos" text[],
"evento" text,
"categoria" text,
"descripcion" text,
"severidad" text);
CREATE TABLE public."notif_state" ("id" integer DEFAULT 1 PRIMARY KEY,
"last_refresh" timestamp with time zone);
CREATE TABLE public."notification_reads" ("user_id" uuid,
"notification_id" bigint,
"read_at" timestamp with time zone DEFAULT now());
CREATE TABLE public."notifications" ("id" bigint PRIMARY KEY,
"created_at" timestamp with time zone DEFAULT now(),
"target_user" uuid,
"evento" text,
"categoria" text,
"severidad" text,
"titulo" text,
"cuerpo" text,
"link" text,
"permisos" text[],
"dedupe_key" text);
CREATE TABLE public."operaciones_actividades" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"turno_id" uuid,
"start_time" timestamp with time zone DEFAULT now(),
"end_time" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"tipo_actividad" character varying,
"status" character varying,
"observaciones" text,
"referencia_ot" text,
"tipo_hora" character varying);
CREATE TABLE public."operaciones_turnos" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"profile_id" uuid,
"ot_id" uuid,
"start_time" timestamp with time zone DEFAULT now(),
"end_time" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"status" character varying,
"supervisor_status" text,
"supervisor_comments" text);
CREATE TABLE public."part_warranties" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"spare_part_id" uuid,
"vehicle_id" uuid,
"work_order_id" uuid,
"provider_id" uuid,
"installed_at" timestamp with time zone DEFAULT now(),
"expires_at" date,
"odometer_at_install" numeric,
"km_limit" integer,
"claimed_at" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"conditions" text,
"status" text,
"claim_notes" text);
CREATE TABLE public."preventive_scheduler_runs" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"run_at" timestamp with time zone DEFAULT now(),
"evaluated" integer DEFAULT 0,
"generated" integer DEFAULT 0,
"details" jsonb,
"triggered_by" text);
CREATE TABLE public."products" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"weight" numeric DEFAULT 0,
"volume_m3" numeric DEFAULT 0,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"length_m" numeric DEFAULT 0,
"width_m" numeric DEFAULT 0,
"thickness_m" numeric DEFAULT 0,
"sku" character varying,
"description" text,
"category" character varying,
"color" character varying);
CREATE TABLE public."profiles" ("id" uuid PRIMARY KEY,
"role_id" uuid,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"shift_id" uuid,
"license_expiration" date,
"first_name" character varying,
"last_name" character varying,
"document_number" character varying,
"phone" character varying,
"mock_password" character varying,
"username" character varying,
"employee_type" character varying,
"document_id" character varying,
"license_type" character varying);
CREATE TABLE public."provider_rates" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"provider_id" uuid,
"price" numeric,
"valid_from" date DEFAULT CURRENT_DATE,
"valid_to" date,
"created_at" timestamp with time zone DEFAULT now(),
"service_name" text,
"unit" text,
"notes" text);
CREATE TABLE public."purchase_order_lines" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"purchase_order_id" uuid,
"spare_part_id" uuid,
"quantity" numeric,
"unit_cost" numeric,
"total_cost" numeric,
"received_quantity" numeric DEFAULT 0);
CREATE TABLE public."purchase_orders" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"order_date" date DEFAULT CURRENT_DATE,
"total_amount" numeric DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"created_by" uuid,
"supplier" text,
"status" text);
CREATE TABLE public."roles" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"created_at" timestamp with time zone DEFAULT now(),
"permissions" jsonb,
"name" character varying,
"description" text);
CREATE TABLE public."route_allowance_rates" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"distance_km" numeric,
"round_trip" boolean DEFAULT true,
"days" integer DEFAULT 1,
"nights" integer DEFAULT 0,
"toll_amount" numeric DEFAULT 0,
"toll_by_type" jsonb,
"meal_per_day" numeric DEFAULT 0,
"lodging_per_night" numeric DEFAULT 0,
"other_amount" numeric DEFAULT 0,
"fuel_price_per_gallon" numeric,
"is_active" boolean DEFAULT true,
"updated_at" timestamp with time zone DEFAULT now(),
"updated_by" uuid,
"code" text,
"name" text,
"origin" text,
"destination" text,
"notes" text);
CREATE TABLE public."route_stops_log" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"transport_request_id" uuid,
"driver_id" uuid,
"arrival_time" timestamp with time zone DEFAULT now(),
"odometer_km" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"stop_type" character varying,
"photo_url" text,
"notes" text);
CREATE TABLE public."route_track_points" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"driver_id" uuid,
"recorded_at" timestamp with time zone,
"latitude" numeric,
"longitude" numeric,
"accuracy_m" numeric,
"speed_mps" numeric,
"leg_order" integer DEFAULT 0,
"distance_m" numeric DEFAULT 0,
"cumulative_m" numeric DEFAULT 0,
"gap_detected" boolean DEFAULT false,
"created_at" timestamp with time zone DEFAULT now());
CREATE TABLE public."service_quotes" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"work_order_id" uuid,
"provider_id" uuid,
"amount" numeric,
"estimated_hours" numeric,
"valid_until" date,
"decided_by" uuid,
"decided_at" timestamp with time zone,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"description" text,
"file_url" text,
"status" text,
"decision_notes" text);
CREATE TABLE public."service_warranties" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"provider_id" uuid,
"vehicle_id" uuid,
"work_order_id" uuid,
"starts_at" timestamp with time zone DEFAULT now(),
"expires_at" date,
"odometer_at_close" numeric,
"km_limit" integer,
"claimed_by_wo_id" uuid,
"claimed_at" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"scope" text,
"status" text);
CREATE TABLE public."sites" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"is_active" boolean DEFAULT true,
"code" text,
"name" text);
CREATE TABLE public."soporte_informes" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"user_id" uuid,
"periodo" date,
"kpis" jsonb,
"enviado_at" timestamp with time zone DEFAULT now(),
"actualizado_at" timestamp with time zone DEFAULT now(),
"dias_desde_cierre" integer DEFAULT 0,
"dias_atraso" integer DEFAULT 0,
"revisado_por" uuid,
"revisado_at" timestamp with time zone,
"logros" text,
"problemas" text,
"acciones" text,
"estado" text,
"comentario" text);
CREATE TABLE public."soporte_parametros" ("valor" numeric,
"clave" text,
"descripcion" text);
CREATE TABLE public."soporte_sla" ("respuesta_horas" numeric,
"solucion_horas" numeric,
"updated_at" timestamp with time zone DEFAULT now(),
"severidad" text);
CREATE TABLE public."spare_part_replenishment_requests" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"spare_part_id" uuid,
"site_id" uuid,
"suggested_quantity" numeric,
"available_at_request" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"resolved_at" timestamp with time zone,
"resolved_by" uuid,
"status" text,
"notes" text);
CREATE TABLE public."spare_part_reservations" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"spare_part_id" uuid,
"work_order_id" uuid,
"quantity" numeric,
"consumed" numeric DEFAULT 0,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"closed_at" timestamp with time zone,
"status" text);
CREATE TABLE public."spare_parts" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"current_stock" numeric DEFAULT 0,
"minimum_stock" numeric DEFAULT 0,
"average_price_pen" numeric DEFAULT 0,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"site_id" uuid,
"unit_price" numeric,
"maximum_stock" numeric,
"warranty_months" integer,
"warranty_km" integer,
"internal_code" character varying,
"name" character varying,
"brand" character varying,
"category" character varying,
"compatibility" text,
"sku" character varying,
"unit" text,
"location" text,
"warranty_conditions" text);
CREATE TABLE public."system_settings" ("updated_at" timestamp with time zone DEFAULT now(),
"key" character varying,
"value" text,
"description" text);
CREATE TABLE public."tire_movements" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"tire_id" uuid,
"current_odometer" numeric,
"cocada" numeric,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"vehicle_id" uuid,
"km_accumulated" numeric,
"cost" numeric,
"provider_id" uuid,
"tipo_movimiento" character varying,
"vehicle_plate" character varying,
"posicion" character varying,
"reason" text,
"position_from" text);
CREATE TABLE public."tires" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"purchase_date" date,
"costo" numeric,
"cocada_original" numeric,
"cocada_actual" numeric,
"total_km_travelled" numeric DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"vehiculo_actual_id" uuid,
"site_id" uuid,
"installed_odometer" numeric,
"retread_count" integer DEFAULT 0,
"retread_cost_total" numeric DEFAULT 0,
"max_retreads" integer DEFAULT 2,
"min_tread_mm" numeric DEFAULT 2.0,
"expected_life_km" integer,
"provider_id" uuid,
"retired_at" timestamp with time zone,
"codigo_interno" character varying,
"marca" character varying,
"modelo" character varying,
"medida" character varying,
"estado" character varying,
"current_vehicle_plate" character varying,
"posicion_actual" character varying,
"dot" character varying,
"serial_number" text,
"retire_reason" text);
CREATE TABLE public."traffic_fines" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"vehicle_id" uuid,
"driver_id" uuid,
"dispatch_id" uuid,
"infraction_date" timestamp with time zone,
"amount" numeric,
"due_date" date,
"responsible_id" uuid,
"paid_amount" numeric,
"paid_at" date,
"site_id" uuid,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"fine_type" text,
"vehicle_plate" text,
"infraction_code" text,
"description" text,
"entity" text,
"ticket_number" text,
"status" text,
"responsibility" text,
"evidence_url" text,
"payment_reference" text,
"notes" text);
CREATE TABLE public."transport_budgets" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"total_amount" numeric,
"consumed_amount" numeric DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"budget_limit" numeric DEFAULT 0,
"code" character varying,
"description" text,
"status" character varying);
CREATE TABLE public."transport_request_components" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"request_id" uuid,
"component_contract_id" uuid,
"requested_weight_kg" numeric,
"requested_volume_m3" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now());
CREATE TABLE public."transport_request_events" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"request_id" uuid,
"actor_id" uuid,
"previous_state" jsonb,
"next_state" jsonb,
"created_at" timestamp with time zone DEFAULT now(),
"action" text);
CREATE TABLE public."transport_request_items" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"transport_request_id" uuid,
"product_id" uuid,
"quantity" numeric DEFAULT 1,
"weight" numeric DEFAULT 0,
"volume_m3" numeric DEFAULT 0,
"length_m" numeric DEFAULT 0,
"width_m" numeric DEFAULT 0,
"is_fragile" boolean DEFAULT false,
"needs_stowage" boolean DEFAULT false,
"needs_forklift" boolean DEFAULT false,
"created_at" timestamp with time zone DEFAULT now(),
"sku" character varying,
"description" text);
CREATE TABLE public."transport_requests" ("id" uuid PRIMARY KEY,
"required_date" timestamp with time zone,
"estimated_weight" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"service_cost" numeric DEFAULT 0.00,
"service_balance" numeric DEFAULT 0.00,
"budget_amount" numeric DEFAULT 0.00,
"cost_per_km" numeric DEFAULT 0.00,
"contract_id" uuid,
"estimated_volume" numeric DEFAULT 0,
"site_id" uuid,
"created_by" uuid,
"budget_shortfall" numeric DEFAULT 0,
"reserved_pen" numeric DEFAULT 0,
"approved_at" timestamp with time zone,
"approved_by" uuid,
"unloading_estimate_pen" numeric DEFAULT 0,
"unloading_required" boolean,
"cost_breakdown" jsonb,
"cost_center_id" uuid,
"operational_approved_pen" numeric DEFAULT 0,
"request_number" character varying,
"requester_name" character varying,
"department" character varying,
"pickup_address" text,
"delivery_address" text,
"cargo_description" text,
"status" character varying,
"request_type" character varying,
"liquidation_notes" text,
"time_window" character varying,
"pickup_department" text,
"pickup_province" text,
"pickup_district" text,
"delivery_department" text,
"delivery_province" text,
"delivery_district" text,
"purchase_order" character varying,
"budget_observation" text,
"cost_source" text,
"cost_override_reason" text,
"attention_mode" text,
"pickup_customer" text,
"pickup_contact" text,
"pickup_phone" text);
CREATE TABLE public."transport_unloading_costs" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"transport_request_id" uuid,
"dispatch_id" uuid,
"contract_id" uuid,
"estimated_pen" numeric DEFAULT 0,
"planned_pen" numeric,
"actual_pen" numeric,
"contract_service_id" uuid,
"expense_id" uuid,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"planned_by" uuid,
"planned_at" timestamp with time zone,
"consumed_by" uuid,
"consumed_at" timestamp with time zone,
"cost_center_id" uuid,
"concept" text,
"description" text,
"status" text,
"provider_name" text,
"void_reason" text);
CREATE TABLE public."trip_advances" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"driver_id" uuid,
"box_id" uuid,
"amount" numeric,
"breakdown" jsonb,
"requested_by" uuid,
"requested_at" timestamp with time zone DEFAULT now(),
"delivered_by" uuid,
"delivered_at" timestamp with time zone,
"movement_id" uuid,
"cancelled_by" uuid,
"context_dispatch_id" uuid,
"maintenance_request_id" uuid,
"needs_approval" boolean DEFAULT false,
"approved_by" uuid,
"approved_at" timestamp with time zone,
"due_at" timestamp with time zone,
"code" text,
"status" text,
"payment_method" text,
"reference" text,
"notes" text,
"cancel_reason" text,
"override_reason" text,
"source" text,
"reason" text,
"reason_code" text,
"vehicle_plate" text,
"evidence_url" text,
"approval_comment" text,
"overdue_flag" text);
CREATE TABLE public."trip_budgets" ("dispatch_id" uuid,
"rate_id" uuid,
"breakdown" jsonb,
"total" numeric DEFAULT 0,
"updated_by" uuid,
"updated_at" timestamp with time zone DEFAULT now());
CREATE TABLE public."trip_settlements" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"dispatch_id" uuid,
"driver_id" uuid,
"advances_total" numeric DEFAULT 0,
"driver_expenses" numeric DEFAULT 0,
"company_expenses" numeric DEFAULT 0,
"rejected_total" numeric DEFAULT 0,
"declared_total" numeric,
"balance" numeric DEFAULT 0,
"box_id" uuid,
"movement_id" uuid,
"closed_by" uuid,
"closed_at" timestamp with time zone,
"reopened_by" uuid,
"reopened_at" timestamp with time zone,
"driver_ack_at" timestamp with time zone,
"driver_ack_by" uuid,
"advance_id" uuid,
"code" text,
"resolution" text,
"status" text,
"notes" text,
"reopen_reason" text);
CREATE TABLE public."user_site_access" ("user_id" uuid,
"site_id" uuid);
CREATE TABLE public."vehicle_costs" ("id" uuid PRIMARY KEY,
"fixed_cost_per_km" numeric DEFAULT 0,
"driver_cost_per_km" numeric DEFAULT 0,
"tolls_estimated_cost" numeric DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"vehicle_type" character varying);
CREATE TABLE public."vehicle_documents" ("id" uuid PRIMARY KEY,
"vehicle_id" uuid,
"issue_date" date,
"expiration_date" date,
"created_at" timestamp with time zone,
"updated_at" timestamp with time zone,
"is_active" boolean DEFAULT true,
"created_by" uuid,
"document_type" character varying,
"file_url" text,
"status" character varying,
"vehicle_plate" text,
"document_number" text,
"issuer" text,
"notes" text);
CREATE TABLE public."vehicle_history_logs" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"changed_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"vehicle_plate" character varying,
"field_changed" character varying,
"old_value" text,
"new_value" text,
"change_reason" text);
CREATE TABLE public."vehicle_incidents" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"vehicle_id" uuid,
"driver_id" uuid,
"dispatch_id" uuid,
"occurred_at" timestamp with time zone,
"estimated_cost" numeric,
"final_cost" numeric,
"insurance_coverage" numeric DEFAULT 0,
"vehicle_damage" boolean DEFAULT false,
"maintenance_request_id" uuid,
"evidence_urls" jsonb,
"site_id" uuid,
"created_by" uuid,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"closed_at" timestamp with time zone,
"incident_type" text,
"severity" text,
"vehicle_plate" text,
"location" text,
"description" text,
"third_parties" text,
"police_report" text,
"insurance_claim_number" text,
"responsibility" text,
"status" text);
CREATE TABLE public."vehicle_lease_contracts" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"vehicle_id" uuid,
"provider_id" uuid,
"monthly_base_fee" numeric DEFAULT 0,
"included_km" integer DEFAULT 0,
"excess_km_rate" numeric DEFAULT 0,
"guaranteed_km" integer DEFAULT 0,
"start_date" date,
"end_date" date,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"rate_amount" numeric,
"included_hours" numeric,
"excess_hour_rate" numeric,
"discount_downtime" boolean DEFAULT true,
"parent_contract_id" uuid,
"site_id" uuid,
"created_by" uuid,
"days_base" integer,
"excess_km_rate_exact" numeric,
"guarantee_amount" numeric,
"contract_type" character varying,
"status" character varying,
"notes" text,
"contract_code" text,
"rate_type" text,
"penalty_terms" text,
"conditions" text,
"file_url" text,
"km_source" text,
"send_to_email" text,
"cc_emails" text);
CREATE TABLE public."vehicle_maintenance_history" ("id" uuid PRIMARY KEY,
"vehicle_id" uuid,
"mileage_at_time" integer,
"user_id" uuid,
"created_at" timestamp with time zone,
"action_type" character varying,
"description" text);
CREATE TABLE public."vehicle_maintenance_records" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"reported_by" uuid,
"started_at" timestamp with time zone,
"completed_at" timestamp with time zone,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"driver_id" uuid,
"dispatch_id" uuid,
"can_continue" boolean,
"latitude" numeric,
"longitude" numeric,
"evidence_paths" jsonb,
"client_operation_id" uuid,
"vehicle_plate" character varying,
"record_type" character varying,
"status" character varying,
"description" text,
"diagnosis" text,
"failure_category" text,
"severity" text,
"audio_path" text);
CREATE TABLE public."vehicle_odometer_logs" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"driver_id" uuid,
"dispatch_id" uuid,
"odometer_value" numeric,
"created_at" timestamp with time zone DEFAULT now(),
"created_by" uuid,
"hours_value" numeric,
"vehicle_plate" text,
"photo_url" text,
"source_event" text,
"status" text,
"notes" text);
CREATE TABLE public."vehicles" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"carrier_id" uuid,
"capacity_weight" numeric,
"capacity_volume" numeric,
"is_active" boolean DEFAULT true,
"created_at" timestamp with time zone DEFAULT now(),
"year" integer,
"weight_capacity" numeric,
"volume_capacity" numeric,
"current_mileage" integer DEFAULT 0,
"last_maintenance_date" date,
"last_maintenance_mileage" integer,
"accumulated_cost" numeric DEFAULT 0.00,
"average_daily_km" integer DEFAULT 0,
"soat_expiration" date,
"technical_review_expiration" date,
"site_id" uuid,
"current_odometer" numeric DEFAULT 0.00,
"current_hours" numeric DEFAULT 0.00,
"responsible_id" uuid,
"is_blocked" boolean DEFAULT false,
"fuel_tank_capacity_gal" numeric,
"expected_km_per_gallon" numeric,
"assigned_driver_id" uuid,
"plate" character varying,
"type" character varying,
"brand" character varying,
"model" character varying,
"status" character varying,
"maintenance_status" character varying,
"internal_code" character varying,
"serial_number" character varying,
"criticality" character varying,
"ownership_status" character varying,
"current_location" character varying,
"block_reason" text);
CREATE TABLE public."work_order_costs" ("id" uuid PRIMARY KEY,
"work_order_id" uuid,
"amount" numeric,
"created_at" timestamp with time zone,
"spare_part_id" uuid,
"provider_id" uuid,
"quantity" numeric DEFAULT 1,
"created_by" uuid,
"cost_type" character varying,
"description" text,
"supplier_name" character varying,
"supplier_ruc" character varying,
"document_type" character varying,
"document_number" character varying,
"evidence_url" text);
CREATE TABLE public."work_order_items" ("id" uuid PRIMARY KEY,
"work_order_id" uuid,
"quantity" integer DEFAULT 1,
"unit_weight" numeric DEFAULT 0,
"total_weight" numeric DEFAULT 0,
"created_at" timestamp with time zone DEFAULT now(),
"sku" character varying,
"description" text);
CREATE TABLE public."work_order_spare_parts" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"work_order_id" uuid,
"spare_part_id" uuid,
"quantity" numeric,
"unit_cost" numeric,
"created_at" timestamp with time zone DEFAULT now());
CREATE TABLE public."work_orders" ("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
"client_id" uuid,
"budget_id" uuid,
"total_weight" numeric,
"total_volume" numeric,
"packages_count" integer,
"required_date" date,
"created_at" timestamp with time zone DEFAULT now(),
"updated_at" timestamp with time zone DEFAULT now(),
"contract_administrator_id" uuid,
"transport_budget_id" uuid,
"parent_work_order_id" uuid,
"budget_amount" numeric DEFAULT 0.00,
"ot_number" character varying,
"origin_address" text,
"destination_address" text,
"destination_district" character varying,
"destination_province" character varying,
"destination_department" character varying,
"status" character varying,
"origin" character varying,
"destination" character varying,
"cargo_details" text,
"origin_department" text,
"origin_province" text,
"origin_district" text);
